- port_limit    : 2
  version       : 2
  low_end       : true
  interfaces    : ["eth1", "eth0"]
  port_info     :  # set eh mac addr
                 - ip         : 192.168.71.130
                   default_gw : 192.168.71.134
                 - ip         : 192.168.73.137
                   default_gw : 192.168.73.138
