ARG BASE_IMAGE=ubuntu:noble
FROM $BASE_IMAGE
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
    pkg-config build-essential m4 \
    linux-tools-common linux-tools-generic linux-tools-$(uname -r) \
    lsb-release software-properties-common gnupg \
    libelf-dev libpcap-dev \
    clang llvm \
    git iproute2 tcpdump \
  && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/tariromukute/xdp-tools.git

WORKDIR /xdp-tools
RUN git checkout xdp_bench_swap_ip && \
    git submodule init && git submodule update

RUN ./configure
RUN make

COPY ./router/ .

ENTRYPOINT [ "sh", "./entrypoint.sh" ]
# ./xdp-bench tx -p swap-macs -e -r eth1