FROM debian:11.7-slim

RUN apt-get update
RUN apt-get install -y git cmake build-essential make g++ libsctp-dev lksctp-tools iproute2 iptables netcat iputils-ping

RUN git clone https://github.com/aligungr/UERANSIM
WORKDIR /UERANSIM

RUN make -j $(nproc)

ENV PATH=$PATH:/UERANSIM/build

WORKDIR /UERANSIM/build/